const projects = [
  {
    projectName: "Impact House",
    projectDescription: "Impact House is built for digital public goods",
    publicGoods: "Impact House make public goods sustainable",
    sustainability:
      "As long as public goods grow up, Impact House can create Impact",
    teamSize: "3",
    submittedDate: 1691258668,
    links: [
      "https://docs.attest.sh/docs/welcome",
      "https://optimism-goerli-bedrock.easscan.org/",
      "https://github.com/tnkshuuhei",
    ],
    website: "https://optimism-goerli-bedrock.easscan.org/",
    github: "https://github.com/tnkshuuhei",
    twitter: "https://twitter.com/_shutanaka",
    payoutAddress: "0x06aa005386F53Ba7b980c61e0D067CaBc7602a62",
    id: 1,
  },
  {
    projectName: "ChainGuard",
    projectDescription:
      "A decentralized network for public blockchain monitoring and analysis.",
    publicGoods:
      "ChainGuard provides public access to blockchain metrics and trends.",
    sustainability:
      "Supported by community grants and open source collaborations.",
    teamSize: "5",
    submittedDate: 1692258668,
    links: [
      "https://docs.chainguard.io/",
      "https://chainguard.network/",
      "https://github.com/chainguard",
    ],
    website: "https://chainguard.network/",
    github: "https://github.com/chainguard",
    twitter: "https://twitter.com/chainguard",
    payoutAddress: "0x07bb007392F54Bb8d980c72e0D0645aBcD7603a63",
    id: 2,
  },
  {
    projectName: "BlockSight",
    projectDescription: "Visual analytics platform for blockchain data.",
    publicGoods:
      "BlockSight offers free insights for emerging blockchain platforms.",
    sustainability: "Revenue generated through premium analytics services.",
    teamSize: "4",
    submittedDate: 1693258668,
    links: [
      "https://docs.blocksight.io/",
      "https://blocksight.platform/",
      "https://github.com/blocksight",
    ],
    website: "https://blocksight.platform/",
    github: "https://github.com/blocksight",
    twitter: "https://twitter.com/blocksight",
    payoutAddress: "0x08cc008392F54Bb8d990c73e0D0656aBcD7604a64",
    id: 3,
  },
  {
    projectName: "TokenView",
    projectDescription:
      "A platform offering deep insights into token economics and usage.",
    publicGoods: "Offers free visualization tools for token distribution.",
    sustainability: "Profits from premium analytical tools and partnerships.",
    teamSize: "6",
    submittedDate: 1694258668,
    links: [
      "https://docs.tokenview.io/",
      "https://tokenview.net/",
      "https://github.com/tokenview",
    ],
    website: "https://tokenview.net/",
    github: "https://github.com/tokenview",
    twitter: "https://twitter.com/tokenview",
    payoutAddress: "0x09dd009393F54Bb9d991c74e0D0677aBcD7615a65",
    id: 4,
  },
  {
    projectName: "CryptoScan",
    projectDescription:
      "Mobile app offering real-time tracking of crypto assets across chains.",
    publicGoods: "CryptoScan allows tracking of 3 assets for free.",
    sustainability: "Monetizes through premium features and ad revenues.",
    teamSize: "4",
    submittedDate: 1695258668,
    links: [
      "https://docs.cryptoscan.io/",
      "https://cryptoscan.app/",
      "https://github.com/cryptoscan",
    ],
    website: "https://cryptoscan.app/",
    github: "https://github.com/cryptoscan",
    twitter: "https://twitter.com/cryptoscanapp",
    payoutAddress: "0x10ee101010F54Bb9d992c75e0D0689aBcD7626a66",
    id: 5,
  },
  {
    projectName: "ChainMetrics",
    projectDescription: "Blockchain analytics and data aggregation tool.",
    publicGoods: "Free access to basic metrics and trends.",
    sustainability: "Subscription model for advanced analytics.",
    teamSize: "5",
    submittedDate: 1696258668,
    links: [
      "https://docs.chainmetrics.io/",
      "https://chainmetrics.net/",
      "https://github.com/chainmetrics",
    ],
    website: "https://chainmetrics.net/",
    github: "https://github.com/chainmetrics",
    twitter: "https://twitter.com/chainmetrics",
    payoutAddress: "0x11ff112112F55Bb9d993d85e0D069AaCcD7736a67",
    id: 6,
  },
  {
    projectName: "DeFiDashboard",
    projectDescription:
      "A one-stop platform to manage and analyze all your DeFi assets.",
    publicGoods: "Basic dashboard functionalities are freely accessible.",
    sustainability: "Offers premium integrations and advanced analytics.",
    teamSize: "7",
    submittedDate: 1697258668,
    links: [
      "https://docs.defidashboard.io/",
      "https://defidashboard.net/",
      "https://github.com/defidashboard",
    ],
    website: "https://defidashboard.net/",
    github: "https://github.com/defidashboard",
    twitter: "https://twitter.com/defidashboard",
    payoutAddress: "0x12gg122123F56Bc9d994d96e0D070BbCcD8846a68",
    id: 7,
  },
  {
    projectName: "BlockStreamz",
    projectDescription:
      "A live streaming platform dedicated to blockchain and crypto events.",
    publicGoods: "Free access to major event streams.",
    sustainability: "Monetizes through ads, sponsorships, and premium streams.",
    teamSize: "8",
    submittedDate: 1698258668,
    links: [
      "https://docs.blockstreamz.io/",
      "https://blockstreamz.com/",
      "https://github.com/blockstreamz",
    ],
    website: "https://blockstreamz.com/",
    github: "https://github.com/blockstreamz",
    twitter: "https://twitter.com/blockstreamz",
    payoutAddress: "0x13hh131314F57Cd9d995e7f0D071DdCcD8957a69",
    id: 8,
  },
];

export default projects;
